name : "obriencj"
title : "obriencj"
tagline : "is a pile of bits"

production_url : "http://obriencj.preoccupied.net"
copyright : "2000-2014"

markdown : "redcarpet"
pygments : true

permalink: "pretty"

author :
  name : "Christopher O'Brien"
  email : "obriencj@gmail.com"
  github : "obriencj"
  twitter : "obriencj"

JB:
  version : "0.3.0"
  BASE_PATH : false
  ASSET_PATH : false
  archive_path : "/archive/"
  categories_path : "/categories/"
  tags_path : "/tags/"
  atom_path : "/atom.xml"
  rss_path : "/rss.xml"
  analytics :
    provider : "google"
    google :
      tracking_id : "UA-47351906-2"
  sharing :
    provider : "tweet"
  comments :
    provider : false


