
name: Build and deploy site


on:
  workflow_call:
  workflow_dispatch:
    inputs:
      inelegant_version:
        description: pelican-inelegant version to build with
        required: true
        type: string
        default: master

  push:
    branches:
      - master
    paths:
      - content/**
      - pelicanconf.py


jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build site
        id: build
        uses: obriencj/pelican-inelegant@master
        with:
          version: ${{ inputs.inelegant_version || 'master' }}

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ steps.build.outputs.output-path }}

  deploy-site:
    runs-on: ubuntu-latest

    needs:
      - build-site

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy site
        id: deploy
        uses: actions/deploy-pages@v2


# The end.
