
name: Build site with pelican-inelegant


on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - content/**
      - pelicanconf.py


jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build site
        run: |
          podman run --rm -it \
            --volume .:/work \
            ghcr.io/obriencj/pelican-inelegant:latest

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: output

  deploy-site:
    runs-on: ubuntu-latest

    needs:
      - build-site

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy site
        id: deploy
        uses: actions/deploy-pages@v2


# The end.
